/**
 * ====================================================================
 * DEEPERNOVA AGENTIC FUZZY DIFF PATCHER
 * ====================================================================
 * Engineered for Antigravity, Cursor, and Windsurf-grade code editing.
 * Solves LLM indentation variations, CRLF/LF discrepancies, and
 * partial whitespace mismatches through a multi-tier matching cascade:
 *
 * Tier 1: Exact Match (Fast path)
 * Tier 2: Line-Trimmed & Indentation-Agnostic Block Match
 * Tier 3: Sliding-Window Levenshtein Similarity Match (Threshold: >= 0.80)
 * ====================================================================
 */

/**
 * Calculates Levenshtein Distance between two strings
 */
export const levenshteinDistance = (a, b) => {
  if (a === b) return 0;
  if (!a.length) return b.length;
  if (!b.length) return a.length;

  const matrix = [];
  for (let i = 0; i <= b.length; i++) matrix[i] = [i];
  for (let j = 0; j <= a.length; j++) matrix[0][j] = j;

  for (let i = 1; i <= b.length; i++) {
    for (let j = 1; j <= a.length; j++) {
      if (b.charAt(i - 1) === a.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1];
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1, // substitution
          matrix[i][j - 1] + 1,     // insertion
          matrix[i - 1][j] + 1      // deletion
        );
      }
    }
  }
  return matrix[b.length][a.length];
};

/**
 * Computes similarity ratio (0.0 to 1.0)
 */
export const similarityRatio = (a, b) => {
  if (a === b) return 1.0;
  const maxLen = Math.max(a.length, b.length);
  if (maxLen === 0) return 1.0;
  const dist = levenshteinDistance(a, b);
  return 1.0 - dist / maxLen;
};

/**
 * Normalizes line endings and whitespace
 */
export const normalizeLineEndings = (str) => {
  return (str || '').replace(/\r\n/g, '\n').replace(/\r/g, '\n');
};

/**
 * Extracts line-trimmed tokens
 */
export const cleanLines = (str) => {
  return normalizeLineEndings(str)
    .split('\n')
    .map(line => line.trim());
};

/**
 * Multi-Tier Search & Replace Diff Engine
 * @param {string} originalContent - Full file source code
 * @param {string} targetSnippet - Snippet generated by AI to replace
 * @param {string} replacement - Replacement code block
 * @param {number} similarityThreshold - Min similarity for tier 3 (default: 0.80)
 * @returns {object} { success: boolean, newContent?: string, error?: string, matchType?: string, confidence?: number }
 */
export const applyFuzzyPatch = (originalContent, targetSnippet, replacement, similarityThreshold = 0.80) => {
  if (typeof originalContent !== 'string') {
    return { success: false, error: 'Konten file asal tidak valid.' };
  }
  if (!targetSnippet || typeof targetSnippet !== 'string') {
    return { success: false, error: 'target_snippet tidak boleh kosong.' };
  }

  const normalizedContent = normalizeLineEndings(originalContent);
  const normalizedTarget = normalizeLineEndings(targetSnippet).trim();
  const normalizedReplacement = normalizeLineEndings(replacement !== undefined ? replacement : '');

  // -------------------------------------------------------------
  // TIER 1: Exact Substring Match
  // -------------------------------------------------------------
  const occurrences = normalizedContent.split(normalizedTarget).length - 1;
  if (occurrences === 1) {
    const updated = normalizedContent.replace(normalizedTarget, normalizedReplacement);
    return {
      success: true,
      newContent: updated,
      matchType: 'exact',
      confidence: 1.0,
      message: 'Patch berhasil diterapkan secara persis (Exact Match).'
    };
  }

  if (occurrences > 1) {
    return {
      success: false,
      error: `target_snippet ditemukan sebanyak ${occurrences} kali dalam file. Ambiguitas! Harap sertakan 2-3 baris konteks sebelum dan sesudah kode yang ingin diganti.`
    };
  }

  // -------------------------------------------------------------
  // TIER 2: Line-Trimmed & Indentation-Agnostic Match
  // -------------------------------------------------------------
  const fileLines = normalizedContent.split('\n');
  const targetLines = normalizedTarget.split('\n').map(l => l.trim()).filter(l => l.length > 0);
  const targetLineCount = targetLines.length;

  if (targetLineCount === 0) {
    return { success: false, error: 'target_snippet kosong setelah dinormalisasi.' };
  }

  for (let i = 0; i <= fileLines.length - targetLineCount; i++) {
    const candidateSlice = fileLines.slice(i, i + targetLineCount);
    const candidateTrimmed = candidateSlice.map(l => l.trim()).filter(l => l.length > 0);

    if (candidateTrimmed.length === targetLines.length) {
      let isLineMatch = true;
      for (let k = 0; k < targetLines.length; k++) {
        if (candidateTrimmed[k] !== targetLines[k]) {
          isLineMatch = false;
          break;
        }
      }

      if (isLineMatch) {
        // Detect leading indentation of first matched line
        const leadingIndentMatch = candidateSlice[0].match(/^(\s*)/);
        const baseIndent = leadingIndentMatch ? leadingIndentMatch[1] : '';

        // Indent replacement if needed
        const replacementLines = normalizedReplacement.split('\n');
        const adjustedReplacement = replacementLines.map((rLine, rIdx) => {
          if (rIdx === 0 || !rLine.trim()) return rLine;
          if (rLine.startsWith('  ') || rLine.startsWith('\t')) return rLine;
          return baseIndent + rLine;
        }).join('\n');

        const newLines = [
          ...fileLines.slice(0, i),
          adjustedReplacement,
          ...fileLines.slice(i + targetLineCount)
        ];

        return {
          success: true,
          newContent: newLines.join('\n'),
          matchType: 'indentation_agnostic',
          confidence: 0.95,
          matchedLineRange: `${i + 1}-${i + targetLineCount}`,
          message: `Patch berhasil diterapkan via Indentation-Agnostic Match (Baris ${i + 1}-${i + targetLineCount}).`
        };
      }
    }
  }

  // -------------------------------------------------------------
  // TIER 3: Sliding Window Levenshtein Fuzzy Similarity Match
  // -------------------------------------------------------------
  let bestScore = 0;
  let bestIndex = -1;
  let bestWindowSize = targetLineCount;

  // Search across dynamic window sizes (±1 line tolerance for extra/missing blank lines)
  for (let windowDelta = -1; windowDelta <= 1; windowDelta++) {
    const windowSize = targetLineCount + windowDelta;
    if (windowSize <= 0 || windowSize > fileLines.length) continue;

    for (let i = 0; i <= fileLines.length - windowSize; i++) {
      const candidateStr = fileLines.slice(i, i + windowSize).map(l => l.trim()).join('\n');
      const targetStr = targetLines.join('\n');
      const score = similarityRatio(candidateStr, targetStr);

      if (score > bestScore) {
        bestScore = score;
        bestIndex = i;
        bestWindowSize = windowSize;
      }
    }
  }

  if (bestScore >= similarityThreshold && bestIndex !== -1) {
    const candidateSlice = fileLines.slice(bestIndex, bestIndex + bestWindowSize);
    const leadingIndentMatch = candidateSlice[0]?.match(/^(\s*)/);
    const baseIndent = leadingIndentMatch ? leadingIndentMatch[1] : '';

    const replacementLines = normalizedReplacement.split('\n');
    const adjustedReplacement = replacementLines.map((rLine, rIdx) => {
      if (rIdx === 0 || !rLine.trim()) return rLine;
      if (rLine.startsWith('  ') || rLine.startsWith('\t')) return rLine;
      return baseIndent + rLine;
    }).join('\n');

    const newLines = [
      ...fileLines.slice(0, bestIndex),
      adjustedReplacement,
      ...fileLines.slice(bestIndex + bestWindowSize)
    ];

    return {
      success: true,
      newContent: newLines.join('\n'),
      matchType: 'fuzzy_levenshtein',
      confidence: Math.round(bestScore * 100) / 100,
      matchedLineRange: `${bestIndex + 1}-${bestIndex + bestWindowSize}`,
      message: `Patch berhasil diterapkan via Fuzzy Matching (Kemiripan: ${Math.round(bestScore * 100)}%, Baris ${bestIndex + 1}-${bestIndex + bestWindowSize}).`
    };
  }

  // If all tiers fail, provide clear diagnostic failure
  return {
    success: false,
    error: `target_snippet tidak cocok dengan isi file (Skor kemiripan tertinggi: ${Math.round(bestScore * 100)}% vs target minimum ${Math.round(similarityThreshold * 100)}%). Gunakan tool 'read_file_lines' untuk membaca kembali baris kode terkini sebelum melakukan edit.`
  };
};

/**
 * Formats file lines with standard line numbering
 * Example Output:
 * [src/app.js:10-15]
 * 10 | const express = require('express');
 * 11 | const app = express();
 */
export const formatLineNumberedWindow = (filePath, content, startLine = 1, endLine = 100) => {
  const normalized = normalizeLineEndings(content || '');
  const lines = normalized.split('\n');
  const total = lines.length;

  const start = Math.max(1, parseInt(startLine) || 1);
  const end = Math.min(total, parseInt(endLine) || total);

  if (total === 0 || (total === 1 && !lines[0])) {
    return `[${filePath}:0-0] (File kosong)`;
  }

  const slice = lines.slice(start - 1, end);
  const padLength = String(end).length;

  const formattedLines = slice.map((line, idx) => {
    const lineNum = String(start + idx).padStart(padLength, ' ');
    return `${lineNum} | ${line}`;
  }).join('\n');

  return `[${filePath}:${start}-${end}] (Total: ${total} baris)\n${formattedLines}`;
};

/**
 * Generates Unified Diff representation (+ for additions, - for deletions)
 */
export const generateUnifiedDiff = (oldText, newText, filePath = 'file') => {
  const oldLines = normalizeLineEndings(oldText || '').split('\n');
  const newLines = normalizeLineEndings(newText || '').split('\n');

  const diffOutput = [`--- a/${filePath}`, `+++ b/${filePath}`];

  let i = 0, j = 0;
  while (i < oldLines.length || j < newLines.length) {
    if (i < oldLines.length && j < newLines.length && oldLines[i] === newLines[j]) {
      diffOutput.push(`  ${oldLines[i]}`);
      i++;
      j++;
    } else if (j < newLines.length && (i >= oldLines.length || !oldLines.slice(i).includes(newLines[j]))) {
      diffOutput.push(`+ ${newLines[j]}`);
      j++;
    } else if (i < oldLines.length) {
      diffOutput.push(`- ${oldLines[i]}`);
      i++;
    }
  }

  return diffOutput.join('\n');
};

/**
 * File Snapshot Memory Registry for Automatic Rollback Safety
 */
const snapshotRegistry = new Map();

export const createSnapshot = (filePath, content) => {
  if (!snapshotRegistry.has(filePath)) {
    snapshotRegistry.set(filePath, []);
  }
  const history = snapshotRegistry.get(filePath);
  history.push({ timestamp: Date.now(), content });
  if (history.length > 10) history.shift();
};

export const getLatestSnapshot = (filePath) => {
  const history = snapshotRegistry.get(filePath);
  if (!history || history.length === 0) return null;
  return history[history.length - 1].content;
};

export const rollbackSnapshot = (filePath) => {
  const history = snapshotRegistry.get(filePath);
  if (!history || history.length === 0) return null;
  const last = history.pop();
  return last ? last.content : null;
};
